### ISSUE TITLE
A possible y2k issue in a long run.

### ISSUE THREAD

**Issue by hemangshah** [nasa/apod-api#10]
If you visit this URL, it will show you an APOD from 27th May 1999, cool, right? But what will happens in 2099? Again a Y2k problem?

https://apod.nasa.gov/apod/ap990527.html

**Comment by toxicmender** [comment]
The Y2k bug (or the Millennium bug & it's variant) doesn't seem likely to occur again to me for the following reasons:
1. The Application logic behind handling of dates, the logic was corrected by most by the time of New years of Y2k (Year 2000).
2. The `unsigned int32` [range: `0` to `(2**31) - 1`] used for number of seconds Since Unix Epoch (1 January 1970), which can (or already has) been mitigated by use of `unsigned int64` [range: `0` to `(2**63) - 1`], which basically renders the bug __solved__ for the _near_ future (until year 292471210648). Those unsigned int sizes are co-related to number of bits of a processor so unless the server NASA is using for APOD is old (32-bit) then until 2038 you're safe, afterwards though they have to switch to a 64-bit (or higher if that becomes available), assuming the service runs until then.

**Comment by JustinGOSSES** [comment]
This repository is for the API that basically grabs data from APOD. It is not APOD itself.
